// src/mantine-core/src/components/UnstyledButton/UnstyledButton.tsx
import React from 'react';

import {
  Box,
  BoxComponentProps,
  polymorphicFactory,
  PolymorphicFactory,
  StylesApiProps,
  useProps,
  useStyles,
} from '../../core';
import classes from './UnstyledButton.module.css';

export type UnstyledButtonStylesNames = 'root';

export interface UnstyledButtonProps
  extends Omit<BoxComponentProps, 'vars' | 'variant'>,
    StylesApiProps<UnstyledButtonFactory> {
  __staticSelector?: string;
}

const defaultProps: Partial<UnstyledButtonProps> = {
  __staticSelector: 'UnstyledButton',
};

export type UnstyledButtonFactory = PolymorphicFactory<{
  props: UnstyledButtonProps;
  stylesNames: UnstyledButtonStylesNames;
  defaultComponent: 'button';
  defaultRef: HTMLButtonElement;
}>;

export const UnstyledButton = polymorphicFactory<UnstyledButtonFactory>(
  (_props: UnstyledButtonProps & { component?: any }, ref) => {
    const props = useProps('UnstyledButton', defaultProps, _props);
    const {
      className,
      component = 'button',
      __staticSelector,
      unstyled,
      classNames,
      styles,
      style,
      ...others
    } = props;

    const getStyles = useStyles<UnstyledButtonFactory>({
      name: __staticSelector!,
      props,
      classes,
      className,
      style,
      classNames,
      styles,
      unstyled,
    });

    return (
      <Box
        {...getStyles('root', { focusable: true })}
        component={component}
        ref={ref}
        type={component === 'button' ? 'button' : undefined}
        {...others}
      />
    );
  }
);

UnstyledButton.classes = classes;
UnstyledButton.displayName = '@mantine/core/UnstyledButton';

// src/mantine-core/src/components/UnstyledButton/UnstyledButton.svelte
<script lang="ts" context="module">
  import type { PolymorphicFactory, StylesApiProps } from '../../core';
  import type { BoxComponentProps } from '../../core/Box/Box.svelte';

  export type UnstyledButtonStylesNames = 'root';

  export interface UnstyledButtonProps
    extends Omit<BoxComponentProps, 'vars' | 'variant'>,
      StylesApiProps<UnstyledButtonFactory> {
    __staticSelector?: string;
  }

  export type UnstyledButtonFactory = PolymorphicFactory<{
    props: UnstyledButtonProps;
    stylesNames: UnstyledButtonStylesNames;
    defaultComponent: 'button';
    defaultRef: HTMLButtonElement;
  }>;
</script>

<script lang="ts">
  export let tag: keyof svelteHTML.IntrinsicElements = 'button';
  export let ref: HTMLElement | null = null;

  type $$Props = UnstyledButtonProps & { tag?: keyof svelteHTML.IntrinsicElements };
</script>

<svelte:element this={tag} class:root={true} bind:this={ref} {...$$restProps}>
  <slot />
</svelte:element>

<style lang="scss">
  .root {
    background-color: transparent;
    cursor: pointer;
    border: 0;
    padding: 0;
    appearance: none;
    font-size: var(--mantine-font-size-md);
    text-align: left;
    text-decoration: none;
    color: inherit;
    touch-action: manipulation;
    -webkit-tap-highlight-color: transparent;
  }
</style>
